### ISSUE TITLE
Quick question about invertory/id get call

### ISSUE THREAD

**Issue by MatthewOakley** [dtt-projects/retail-app#18]
Hey everyone,

I was making a GET call on this url:
https://api.us-south.apiconnect.appdomain.cloud/lasermusibmcom-dev/sb/capstone-1.0/Inventory/21
I sometimes receive response codes of 404 or 200. If I keep making the request it will eventfully succeed and send data back. I was wondering what you guys are seeing on your end.
@Degilio 
@buzzettim 

All the best,
Matt Oakley

**Comment by buzzettim** [comment]
Taking a look - do you get any messages coming back in the response body?

**Comment by MatthewOakley** [comment]
This is the response I get back

{ "httpCode":"404", "httpMessage":"Not Found", "moreInformation":"The requested URL was not found on this server" }

**Comment by buzzettim** [comment]
Just checked the logs - looks like the password our services use expired. I need to temporarily disable the API for a bit while I get it fixed. I'll post here and in the slack channel when it's ready. Working on it now....

**Comment by MatthewOakley** [comment]
Sounds good
Thanks for the quick response!

**Comment by buzzettim** [comment]
I think we are good - can you give it a try? I just reenabled the services.

**Comment by MatthewOakley** [comment]
Looks good on my end.
Thank you!
